Dev
EtherDaler/Dungeon-Knight pull request #7
Opened 2022-05-22 19:30 UTC by EtherDaler

2022-12-21 18:12 UTC, akhtyamovpavel requested changes
Добрый вечер!

Провел ревью кода - буду ждать обновления!

2022-12-21 18:12 UTC, akhtyamovpavel commented on src/decorators.py
> +     return wrapper
А threadpool для этих целей не подходит? Или для каких целей этот код нужен?

2022-12-21 18:12 UTC, akhtyamovpavel commented on src/Boss.py
> +    def __init__(self, boss: object, skills_list: list, ult: int):
Если аргументов больше 2, то большая часть из них должна быть именованной

2022-12-21 18:12 UTC, akhtyamovpavel commented on src/Boss.py
> +            self.boss.hp = self.boss.hp
Зачем?

2022-12-21 18:12 UTC, akhtyamovpavel commented on src/Boss.py
> +        self.stop_fast(speed, tm)
Может быть, сделать слоты, в которых применять паттерн Стратегия?

2022-12-21 18:12 UTC, akhtyamovpavel commented on src/Boss.py
> +            sphere.coords[1] += sphere.speed
Не дублирование ли кода здесь?

2022-12-21 18:12 UTC, akhtyamovpavel commented on src/Boss.py
> +class Boss_fases:
1 класс - 1 файл

2022-12-21 18:12 UTC, akhtyamovpavel commented on src/Boss.py
> +class Boss(SimpleEnemy):
Нужна обновленная архитектура UML-проекта

2022-12-21 18:12 UTC, akhtyamovpavel commented on src/Boss.py
> +        self.fases = Boss_fases(self, fas1, fas2)
`faces` - если речь идет про лица

2022-12-21 18:12 UTC, akhtyamovpavel commented on src/Boss.py
> +        exec(f'self.skills.{skill}({s})')
Хотя бы key-value

2022-12-21 18:12 UTC, akhtyamovpavel commented on src/Boss.py
> +        exec(f'self.skills.{skill}({s})')
Вы знаете, что exec может быть небезопасным?

2022-12-21 18:12 UTC, akhtyamovpavel commented on src/Boss.py
> +    def use_skill(self, kd: list, **kwargs):
kd - это `cooldown`? Если так, то надо так и делать

2022-12-21 18:12 UTC, akhtyamovpavel commented on src/Boss.py
> +    def active(self):
Может быть `make_move`?

2022-12-21 18:12 UTC, akhtyamovpavel commented on src/Enemy.py
> +class SimpleEnemy(Sprite):
Логика движения не отделена от интерфейса - а это надо сделать

2022-12-21 18:12 UTC, akhtyamovpavel commented on src/Enemy.py
> +        return on_line == 0 and between <= 0
В модуль "Математика" необходимо вытащить этот код

2022-12-21 18:12 UTC, akhtyamovpavel commented on src/Enemy.py
> +            self.to = True
Может быть, это стоит выносить в отдельную функцию?

2022-12-21 18:12 UTC, akhtyamovpavel commented on src/Enemy.py
> +            self.state = 5
Для этого нужен enum

2022-12-21 18:12 UTC, akhtyamovpavel commented on src/Game.py
> +        self.screen = pygame.display.set_mode(
Игра не должна быть GOD-объектом

2022-12-21 18:12 UTC, akhtyamovpavel commented on src/Game.py
> +            self.animate(self.player.draw(2), tuple(self.player.coords))
Для этого есть паттерн Команда

2022-12-21 18:12 UTC, akhtyamovpavel commented on src/Game.py
> +            if self.game_stage == "main menu":
Строки - в константы

2024-01-26 15:18 UTC, EtherDaler commented on src/decorators.py
> +     return wrapper
Этот декоратор я написал, чтобы потом обертывать в него некоторые функции, которые будут действовать некоторое время в фоне, например бафы на увеличение урона. Увеличение урона действует n секунд, после должно пропасть, таких способностей много. И я обернул такие методы классов, чтобы потом не было проблем с потоками. Можно было бы использовать threadpool, но это бы сделало код менее читаемым, потому что при вызове этих функций пришлось бы инициализировать тредпул и заносить туда уже эти функции перед их вызовом.

2024-01-27 18:28 UTC, akhtyamovpavel requested changes
Добрый вечер!

Посмотрел код ещё раз - некоторая часть комментариев не была исправлена, часть исправлений я увидел. Буду ждать обновлённую версию!

2024-01-27 18:28 UTC, akhtyamovpavel commented on src/Boss.py
> +    def __init__(self, boss: object, skills_list: list, ult: int):
Это неименованные аргумент

2024-01-27 18:28 UTC, akhtyamovpavel commented on src/Boss.py
> +        self.fases = Boss_fases(self, fas1, fas2)
Не исправлено

2024-01-27 18:28 UTC, akhtyamovpavel commented on src/Boss.py
>      def activate_fas2(self):
`phase`

2024-01-27 18:28 UTC, akhtyamovpavel commented on src/Models.py
> +    def __init__(self, image: object, coords: list, hp: int = 100, k_hp: int = 12, armor: float = 0, k_armor: int = 1, speed: int = 150, view_range: int = 100,
Использовать паттерн Builder

2024-01-27 18:28 UTC, akhtyamovpavel commented on src/Models.py
>      def __init__(self, range: int, speed: int, damage: int, coords: list, orientation: int, image: str, on_fly: bool):
Лишних файлов в проекте не должно быть

2024-01-27 18:28 UTC, akhtyamovpavel commented on src/decorators.py
> +     return wrapper
Не поверите, код будет не очень большой для такого функционала.

2024-01-27 18:28 UTC, akhtyamovpavel commented on src/decorators.py
> +def mult_threading(func):
Название функции ни о чём не говорит. Необходимо давать нормальные названия функциям.

2024-10-14 21:50 UTC, merged